services:
  client.customers:
    image: ${DOCKER_REGISTRY-}client.customers
    build:
      context: .
      dockerfile: src/Client.Customers.Presentation/Dockerfile
    ports:
      - "7000:7000"
      - "7001:7001"
    networks:
      shopeefood-clone-net:
        
  sync-images:
    image: alpine
    depends_on:
      - client.customers
    volumes:
      - images-volume:/uploads/images
      - D:/Internship/Code/Demo/ShopeeFood_Clone/images:/host-images
      - ./sync-images.sh:/sync-images.sh
    command: sh /sync-images.sh

volumes:
  images-volume:
    external: true
      
networks:
  shopeefood-clone-net:
    external: true
