# This is a generated file. Not intended for manual editing.
services:
  client.customers:
    build:
      context: "D:\\Internship\\Code\\Demo\\ShopeeFood_Clone\\WebMvc_Customers"
      dockerfile: "src/Client.Customers.Presentation/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Client.Customers.Presentation.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "client.customers:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "D:\\Internship\\Code\\Demo\\ShopeeFood_Clone\\WebMvc_Customers\\src\\Client.Customers.Presentation:/app:rw"
    - "D:\\Internship\\Code\\Demo\\ShopeeFood_Clone\\WebMvc_Customers:/src:rw"
    - "C:\\Users\\hoa.nguyen\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\hoa.nguyen\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.6\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.5\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\hoa.nguyen\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_26_10_40_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
